---
- name: Install Windows Patches
  hosts: all
  tasks:
  - name: Choose which Windows updates to install
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      server_selection: managed_server
      reboot: yes
