---
- name: Install Windows Patches
  hosts: all
  server_selection: managed_server
  gather_facts: false
  tasks:
    - name: Choose which Windows updates to install
      win_updates:
        category_names:
         - SecurityUpdates
         - CriticalUpdates
         - UpdateRollups
      reboot: yes
